#@TYPE: Machine
#@NAME: parallella1-hdmi
#@DESCRIPTION: Adapteva Parallella Board with hdmi support

require conf/machine/include/parallella-common.inc

EXTRA_IMAGEDEPENDS += "parallella-hdmi-bitstream"

# specify devicetree from kernel source
#KERNEL_DEVICETREE = "zynq-parallella.dtb"
KERNEL_DEVICETREE = "zynq-parallella_7010.dtb"
# select the devicetree source - built from kernel source or
# externally built from fpga design with Vitis
# SPECIFIED SEPARTELY for headless and hdmi images see parallella.conf
#PREFERRED_PROVIDER_virtual/dtb ?= "linux-parallella"
PREFERRED_PROVIDER_virtual/dtb ?= "parallella-hdmi-dtb"
