#@TYPE: Machine
#@NAME: parallella
#@DESCRIPTION: Adapteva Parallella Board headless

require conf/machine/include/parallella-common.inc

EXTRA_IMAGEDEPENDS += "parallella-bitstream"

# specify devicetree from kernel source
#KERNEL_DEVICETREE = "zynq-parallella-headless.dtb"
KERNEL_DEVICETREE = "zynq-parallella-headless_7010.dtb"
# select the devicetree source - built from kernel source or
# externally built from fpga design with Vitis
# SPECIFIED SEPARTELY for headless and hdmi images see parallella-hdmi.conf
#PREFERRED_PROVIDER_virtual/dtb ?= "linux-parallella"
PREFERRED_PROVIDER_virtual/dtb ?= "parallella-dtb"
